name: Deploy Production Environment

on:
    push:
        branches:
            - deploy

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Create .env file
              run: |
                  echo "CONTACT_PAGE_HOOK=${{ secrets.CONTACT_PAGE_HOOK }}" >> .env
                  echo "APPLY_PAGE_HOOK=${{ secrets.APPLY_PAGE_HOOK }}" >> .env

            - name: Build and Run Docker Container Locally
              run: |
                  docker build -t solync-landing:deploy .
                  docker stop solync-landing-deploy || true
                  docker rm solync-landing-deploy || true
                  docker run -d \
                    --name solync-landing-deploy \
                    --env-file .env \
                    --restart unless-stopped \
                    -p 3001:3000 \
                    solync-landing:deploy
